spring:
  application:
    name: project-management

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE